version: '3.7'

services:
  zookeeper:
    image: sauljabin/kafka:latest
    environment:
      - TZ=America/Guayaquil
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
      - zookeeper_logs:/kafka/logs
    command: zookeeper config/zookeeper.properties

  kafka:
    image: sauljabin/kafka:latest
    depends_on:
      - zookeeper
    restart: on-failure
    environment:
      - TZ=America/Guayaquil
    ports:
      - 9093:9093
    volumes:
      - kafka_data:/data
      - kafka_logs:/kafka/logs
    command: kafka config/server.properties

volumes:
  kafka_data:
  kafka_logs:
  zookeeper_data:
  zookeeper_logs:
  zookeeper_datalog:
