version: '3.9'

services:
  zookeeper:
    image: sauljabin/kafka:latest
    environment:
      - TZ=America/Guayaquil
    restart: on-failure
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
      - zookeeper_logs:/kafka/logs
      - ./config/zookeeper/zookeeper.properties:/kafka/config/zookeeper.properties
    command: zookeeper

  kafka:
    image: sauljabin/kafka:latest
    environment:
      - TZ=America/Guayaquil
      - JMX_PORT=19095
    depends_on:
      - zookeeper
    restart: on-failure
    ports:
      - 19092:19092
      - 19095:19095
    volumes:
      - kafka_data:/data
      - kafka_logs:/kafka/logs
      - ./config/zookeeper/kafka.properties:/kafka/config/kafka.properties
    command: kafka

volumes:
  kafka_data:
  kafka_logs:
  zookeeper_data:
  zookeeper_logs:
  zookeeper_datalog:

networks:
  default:
    external: true
    name: kafka
