version: '3.9'

services:
  kafka:
    image: sauljabin/kafka:latest
    environment:
      - TZ=America/Guayaquil
    restart: on-failure
    ports:
      - 9093:9093
    volumes:
      - kafka_data:/data
      - kafka_logs:/kafka/logs
      - ./config/kraft/server.properties:/kafka/config/server.properties
    command: |
      bash -c 'kafka-storage format --ignore-formatted --config config/server.properties --cluster-id $(kafka-storage random-uuid) && kafka config/server.properties'

volumes:
  kafka_data:
  kafka_logs:

networks:
  default:
    external: true
    name: kafka
