version: '3.9'

services:
  kafka:
    image: sauljabin/kafka:latest
    environment:
      - TZ=America/Guayaquil
      - JMX_PORT=19095
    restart: on-failure
    ports:
      - 19092:19092
      - 19095:19095
    volumes:
      - kafka_data:/data
      - kafka_logs:/kafka/logs
      - ./config/kraft/kafka.properties:/kafka/config/kafka.properties
    command: kafka-raft

volumes:
  kafka_data:
  kafka_logs:

networks:
  default:
    external: true
    name: kafka
