version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.4
    environment:
      - TZ=America/Guayaquil
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888
      - ZOO_LOG4J_PROP=INFO,ROLLINGFILE
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
      - zookeeper_logs:/logs

  kafka:
    image: kafka
    environment:
      - TZ=America/Guayaquil
    ports:
      - 9093:9093
    volumes:
      - kafka_data:/data
      - kafka_logs:/kafka/logs
      - kafka_certificates:/certs
    command: >
      --override broker.id=1
      --override log.dirs=/data
      --override zookeeper.connect=zookeeper:2181
      --override listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:SSL
      --override inter.broker.listener.name=INTERNAL
      --override listeners=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      --override advertised.listeners=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      --override ssl.keystore.location=/certs/kafka.server.keystore.jks
      --override ssl.truststore.location=/certs/kafka.server.truststore.jks
      --override ssl.key.password=${SERVER_PASS}
      --override ssl.keystore.password=${SERVER_PASS}
      --override ssl.truststore.password=${SERVER_PASS}

volumes:
  kafka_data:
  kafka_logs:
  zookeeper_data:
  zookeeper_logs:
  zookeeper_datalog:
  kafka_certificates:
    external: true
