version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.4
    environment:
      - TZ=America/Guayaquil
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888
      - ZOO_LOG4J_PROP=INFO,ROLLINGFILE
    ports:
      - 2181:2181
    networks:
      - broker_network
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
      - zookeeper_logs:/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M

  broker:
    image: broker
    environment:
      - TZ=America/Guayaquil
    ports:
      - 9093:9093
    networks:
      - broker_network
    volumes:
      - broker_data:/data
      - broker_logs:/kafka/logs
    command: >
      --override broker.id=1
      --override log.dirs=/data
      --override zookeeper.connect=zookeeper:2181
      --override listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      --override inter.broker.listener.name=INTERNAL
      --override listeners=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      --override advertised.listeners=INTERNAL://broker:9092,EXTERNAL://localhost:9093
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  broker_data:
    external: true
  broker_logs:
    external: true
  zookeeper_data:
    external: true
  zookeeper_logs:
    external: true
  zookeeper_datalog:
    external: true

networks:
  broker_network:
    external: true
